import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsBoolean,
  IsIn,
  IsObject,
  IsOptional,
  IsString,
  Length,
  MaxLength,
} from 'class-validator';

export class CreateConnectionRequestDto {
  @ApiProperty({ example: 'https://shop.example.com', maxLength: 2048 })
  @IsString()
  @Length(1, 2048)
  siteUrl!: string;

  @ApiProperty({
    description: 'Raw installation key generated by the plugin',
    minLength: 32,
    maxLength: 256,
  })
  @IsString()
  @Length(32, 256)
  installationKey!: string;

  @ApiPropertyOptional({ example: 'My shop', maxLength: 100 })
  @IsOptional()
  @IsString()
  @Length(1, 100)
  siteName?: string;

  @ApiPropertyOptional({ example: { wpVersion: '6.8', pluginVersion: '1.0.0' } })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}

export class UpdateWordPressSiteDto {
  @ApiPropertyOptional({ example: 'New name', maxLength: 100 })
  @IsOptional()
  @IsString()
  @Length(1, 100)
  name?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  enabled?: boolean;
}

export class CreateEditSessionDto {
  @ApiPropertyOptional({ maxLength: 100_000 })
  @IsOptional()
  @IsString()
  @MaxLength(100_000)
  inputText?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsObject()
  inputJson?: Record<string, unknown>;
}

export class CompleteEditSessionDto {
  @ApiPropertyOptional({ maxLength: 100_000 })
  @IsOptional()
  @IsString()
  @MaxLength(100_000)
  outputText?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsObject()
  outputJson?: Record<string, unknown>;
}

export class AssetDirectionDto {
  @ApiPropertyOptional({ enum: ['input', 'output'], default: 'input' })
  @IsOptional()
  @IsIn(['input', 'output'])
  direction?: 'input' | 'output';
}
